ALTER TABLE employees
ADD COLUMN email_address VARCHAR(255) NOT NULL,
    ADD COLUMN mobile_number VARCHAR(32) NOT NULL,
    ADD COLUMN address_line_1 VARCHAR(255) NOT NULL,
    ADD COLUMN address_line_2 VARCHAR(255),
    ADD COLUMN city VARCHAR(255) NOT NULL,
    ADD COLUMN postcode VARCHAR(255) NOT NULL,
    ADD COLUMN country VARCHAR(255) NOT NULL
